FROM python:3.11

WORKDIR /code
RUN python -m site

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY . /code
COPY modified_libraries /usr/local/lib/python3.11/site-packages

EXPOSE 80
ENV FORWARDED_ALLOW_IPS *


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--forwarded-allow-ips", "*", "--proxy-headers"]

